name: badges
description: A flutter package for creating badges.
version: 0.0.3
author: Daniyil Yakovlev <danny.yakovlev@gmail.com>
homepage: https://github.com/yadaniil/flutter_badges

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


environment:
  sdk: ">=1.19.0 <2.0.0"


flutter:
